### ISSUE TITLE
Link to CV doesn't work

### ISSUE THREAD

**Issue by daltonfury42** [kabaliisa/portifolio-latest#1]
I was randomly going through your [site](https://kabaliisasolomon.netlify.app/), clicked on the Download Resume Button, and it gave Access Denied. You might want to give public read only access on the link for recruiters etc? 

https://drive.google.com/file/d/1GhNtS8u2xHW2im4hLxFHWvUVYXHaIpkD/view?ths=true
![image](https://user-images.githubusercontent.com/11256376/109911955-1c50d280-7cd1-11eb-8638-ff2e2ac66fc5.png)

**Comment by kabaliisa** [comment]
@daltonfury42 thanks for the observation. I have corrected the link restrictions and updated the Resume too.

**Comment by daltonfury42** [comment]
Awesome, keep learning!
